dist: trusty
sudo: false

language: cpp

compiler:
  - gcc

python:
  - 3.6

branches:
  only:
    - dev

addons:
  apt:
    packages:
      - python3-pip

install:
  - pip3 install --user -r ./requirements.txt
  - pip3 install --user -r ./requirements-test.txt
  - git clone https://github.com/simulationcraft/simc.git SimulationCraft
  - cd SimulationCraft
  - make
  - cd ..

script:
  # Test simulation_objects and collect coverage information at the same time.
  - coverage run --source=bloodytools/simulation_objects --omit=*_tests.py ./bloodytools/simulation_objects/simulation_objects_tests.py

# makes travis send a notification to discord with these values
before_script:
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - export PYTHON_VERSION="$(python --version)"

# makes travis send a notification to discord
after_success:
  - chmod +x success.sh
  - ./success.sh
  - coveralls

# makes travis send a notification to discord
after_failure:
  - chmod +x fail.sh
  - ./fail.sh

# no email notifications, this shall be handled/viewed via discord
notifications:
  email: false
